const initFormData = {
    gender: '',
    compoundId: 0.1,     //o.1 is the id for new compound
    roomType: 'single room',
    areaLocated: 'Damico',
    noOfWindows: 0,
    noOfTenantPermitted: 1,
    noOfRoomsPerBath: 1,
    noOfRoomsPerToilet: 1,
    comp_name: '',
    comp_type: 'Storey building',
    roomAreaUnit: 'sqr meter',
    roomArea: 0,
    latitude: 0,
    longitude: 0,
    room_image: null,
    comp_image: null,
    room_yearlyPrice: 0,
    discount: 0,
    inspection_price: 0,
    smoking: false,
    animals: false,
    children: false,
    partying: false,
    check_in: null,
    check_out: null,
    agentComment: '',
    extraRules: '',
    airCondition: false,
    garage: false,
    wellWater: false,
    borehole: false,
    generator: false,
    powerSupply: false,
    kitchen: false,
    washingMachine: false,
    cleaner: false,
    bathtube: false,
    flatscreenTV: false,
    swimmingPool: false,
    ownerType: 'individual'
};

export default initFormData;